/**
 * Bancos e instituições do Sistema Financeiro Nacional mais usados, incluindo
 * as financeiras de veículos (para quitação de financiamento). Serve como
 * sugestão nos campos de banco — o usuário pode escolher ou digitar outro.
 */
export const BANKS: string[] = [
  // Grandes bancos
  "Banco do Brasil",
  "Caixa Econômica Federal",
  "Bradesco",
  "Itaú Unibanco",
  "Santander",
  "Banco Safra",
  "BTG Pactual",
  "Citibank",
  "Banco Votorantim (BV)",
  "Banrisul",
  "BRB - Banco de Brasília",
  "Banco do Nordeste",
  "Banco da Amazônia",
  "Banco Mercantil do Brasil",
  "Banestes",
  // Cooperativas
  "Sicoob",
  "Sicredi",
  "Unicred",
  "Cresol",
  "Ailos",
  // Digitais / fintechs
  "Nubank",
  "Banco Inter",
  "C6 Bank",
  "Banco Original",
  "Neon",
  "Agibank",
  "Banco Bari",
  "Will Bank",
  "PagBank (PagSeguro)",
  "Mercado Pago",
  "Banco Digio",
  "Banco Next",
  "Banco Modal",
  "Banco Rendimento",
  // Crédito / consignado / veículos
  "Banco Pan",
  "Banco BMG",
  "Banco Daycoval",
  "Banco Sofisa",
  "Banco Topázio",
  "Banco Semear",
  "Omni Banco",
  "Creditas",
  "Portoseg (Porto Seguro)",
  // Financeiras de veículos
  "Aymoré (Santander Financiamentos)",
  "BV Financeira",
  "Bradesco Financiamentos",
  "Itaú Financiamentos",
  "Banco Pan Financiamentos",
  "Omni Financeira",
  "RCI Brasil (Renault/Nissan)",
  "Banco Volkswagen",
  "Banco Toyota do Brasil",
  "Banco GMAC (Chevrolet)",
  "Banco Honda",
  "Banco Fidis (Fiat/Stellantis)",
  "Banco PSA (Peugeot/Citroën)",
  "Banco Mercedes-Benz",
  "Banco CNH Industrial",
  "Banco Yamaha Motor",
  "Consórcio Nacional Honda",
  // Consórcios/administradoras comuns
  "Rodobens Consórcio",
  "Embracon Consórcio",
  "Porto Seguro Consórcio",
  "Bradesco Consórcio",
  "Itaú Consórcio",
  "Santander Consórcio",
  "Caixa Consórcio",
  "Magalu Consórcio",
];
